blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/osiegmar/logback-gelf/discussions
    about: For questions and general discussions please use Discussions and do not open an issue.
